# variable "vpc_id" {
#   description = "The ID of the VPC created in the VPC module."
#   type        = string
# }

variable "cluster_name" {
  description = "The name of the ECS cluster."
  type        = string
  default     = "csntp_cluster"
}

variable "execution_role_arn" {
  description = "The ARN of the IAM role that ECS tasks will use."
  type        = string
}

# variable "db_password" {
#   description = "The database password generated by the security module and stored in Parameter Store."
#   type        = string
# }

variable "route53_zone_id" {
  description = "Zone ID of Route 53 domain"
  type        = string
}

variable "domain_name" {
  description = "Domain name"
  type        = string
}

variable "rds_identifier" {
  description = "The identifier for the RDS instance."
  type        = string
}

variable "instance_class" {
  description = "The instance class for the RDS instance."
  type        = string
}

variable "iam_database_authentication_enabled" {
  description = "Enable IAM database authentication."
  type        = bool
}

variable "rds_db_name" {
  type    = string
  default = "csntp_db"
}

variable "database_username" {
  type    = string
  default = "admin"
}

variable "pub_access" {
  type    = bool
  default = false
}

variable "hosted_zone_id" {
    type    = string
}

variable "alb_dns_name" {
  type = string
  # default = module.vpc.alb_dns_name
}