name: Deploy Infrastructure

on:
    workflow_dispatch:
      inputs:
        terraform_action:
          type: choice
          description: select terraform action
          options:
          - apply
          - destroy
          required: true
  


# on:
#   push:
#     branches:
#       - main

permissions:
  contents: read
  id-token: write

jobs:
  deploy_infra:
    name: Deploy AWS Infrastructure
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: s3-bucket

    steps:
      - uses: actions/checkout@v4

      - name: Setup Cred
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::493475752675:role/GithubActions
          role-session-name: github-actions

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.6.6"

      - name: Terraform Init
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.14.3
          tf_actions_subcommand: 'init'
          tf_actions_working_dir: './s3-bucket'
          tf_actions_comment: true
  
      - name: Terraform plan
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.14.3
          tf_actions_subcommand: 'plan'
          tf_actions_working_dir: './s3-bucket'
          tf_actions_comment: true
  
      - name: Terraform apply
        if: ${{ github.event.inputs.terraform_action == 'apply' }}
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.14.3
          tf_actions_subcommand: ${{ github.event.inputs.terraform_action }}
          tf_actions_working_dir: './s3-bucket'
          tf_actions_comment: true
          args: '-auto-approve'
        
      - name: Terraform destroy
        if: ${{ github.event.inputs.terraform_action == 'destroy' }}
        uses: hashicorp/terraform-github-actions@master
        continue-on-error: true
        with:
          tf_actions_version: 0.14.3
          tf_actions_subcommand: ${{ github.event.inputs.terraform_action }}
          tf_actions_working_dir: './s3-bucket'
          tf_actions_comment: true
          args: '-auto-approve'
  